### ISSUE TITLE
Add pip and httpie

### ISSUE THREAD

**Issue by jamlen** [Hewlett-Packard-ESS/docker-devenv#1]
Since this already has Python installed, it would be good to have `pip` installed too.

See [installing-pip](https://pip.pypa.io/en/latest/installing.html)

Once pip is installed, having [`httpie`](http://httpie.org) would make posting and getting JSON much better!

**Comment by Stono** [comment]
@jamlen I've added pip to docker-base as that is where python gets installed, I'll add httpie to devenv now.

https://github.com/Hewlett-Packard-ESS/docker-base/commit/2d64c51db93bd957b8ec6f9e71e2c53c2a1bb182

**Comment by Stono** [comment]
@jamlen httpie is done too - will take a while for a it to build in the registry https://github.com/Hewlett-Packard-ESS/docker-devenv/commit/34ffb17d6524bceda0dccac0aca096b17c040c51
